Update emulator_test.yml

diff --git a/.github/workflows/emulator_test.yml b/.github/workflows/emulator_test.yml
--- a/.github/workflows/emulator_test.yml
+++ b/.github/workflows/emulator_test.yml
@@ -93,17 +93,17 @@ jobs:
             # انسخ الفيديو من المحاكي
             adb pull /sdcard/demo.mp4 demo.mp4
 
-      - name: Convert video to webm
-        run: |
-          if ! command -v ffmpeg &> /dev/null
-          then
-            echo "ffmpeg not found, installing..."
-            sudo apt-get update -y
-            sudo apt-get install -y ffmpeg
-          else
-            echo "ffmpeg already installed"
-          fi
-          ffmpeg -i demo.mp4 -c:v libvpx-vp9 -b:v 1M demo.webm
+      # - name: Convert video to webm
+      #   run: |
+      #     if ! command -v ffmpeg &> /dev/null
+      #     then
+      #       echo "ffmpeg not found, installing..."
+      #       sudo apt-get update -y
+      #       sudo apt-get install -y ffmpeg
+      #     else
+      #       echo "ffmpeg already installed"
+      #     fi
+      #     ffmpeg -i demo.mp4 -c:v libvpx-vp9 -b:v 1M demo.webm
 
 
 
